version: '3.1'

volumes:
  es_data:

services:

  elasticsearch:  # https://github.com/elastic/elasticsearch-docker
    build:
      context: ./elasticsearch/
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es_data:/usr/share/elasticsearch/data
    ports:  # exposed to localhost only
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      PING_USERNAME: "kibanaro"  # TODO: use env vars or secrets here
      PING_PASSWORD: "kibanaro"
    networks:
      - elk

  kibana:  # https://github.com/elastic/kibana-docker
    build:
      context: kibana/
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "0.0.0.0:443:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    secrets:
      - kibana_ssl_cert.pem
      - kibana_ssl_key.pem

  apm_server:  # https://github.com/elastic/apm-server-docker
    build:
      context: apm-server
    container_name: apm_server
    ports: ['8200:8200']
    networks:
      - elk
    command: -e -E 'apm-server.host=0.0.0.0:8200'
    depends_on: ['elasticsearch', 'kibana']

secrets:
  kibana_ssl_cert.pem:
    file: /etc/letsencrypt/live/apm.icelinkapp.com/cert.pem
  kibana_ssl_key.pem:
    file: /etc/letsencrypt/live/apm.icelinkapp.com/privkey.pem

networks:
  elk:
    driver: bridge
