---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml

# Configuring kibana docs - https://www.elastic.co/guide/en/kibana/current/settings.html
#

server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200

# https://www.elastic.co/guide/en/kibana/current/production.html#enabling-ssl
server.ssl.enabled: true
server.ssl.key: /run/secrets/kibana_ssl_key.pem
server.ssl.certificate: /run/secrets/kibana_ssl_cert.pem

## Custom configuration
# TODO: move it to env vars or something
elasticsearch.username: "kibanaserver"
elasticsearch.password: "Dyd2Swequo"

# TODO: move it to env vars or something
searchguard.cookie.password: "NuCodyuidlabdetnefjafavDigAshsevyewagNoblysIvEmsUt"

# X-pack settings
# https://www.elastic.co/guide/en/kibana/6.2/settings-xpack-kb.html
xpack.apm.ui.enabled: true
# x-pack security settings - https://www.elastic.co/guide/en/kibana/6.2/security-settings-kb.html
xpack.security.enabled: false
